#the text that shows up in the tab & on google
title: "Liv Grant, student & filmmaker"

#the text that shows up in the description on google
description: "Oxford grad, ex-BBC, etc. etc."

#the text that shows up as the header on your page
header: "Liv Grant"

#the text that shows up under the header on your page
elevator: "Hi, I'm a human being with feelings, fears, and fishes, just like you"
# google_analytics: UA-xxxxxxxx-x


#-------
# Kooky stuff:

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed

plugins:
  - jekyll-seo-tag